### ISSUE TITLE
[SOLVED] Question about how to compile a perfect libass.dll

### ISSUE THREAD

**Issue by ipid** [rigaya/build_scripts#2]
Since I want to implement my own extended ASS directive, I am trying to compile libass-9.dll using the commands in your `build_ffmpeg_dll.sh` script. I tried to build all the dependencies of libass and then ran the following command in the last step:

```bash
make -C libass -j8 libass.la
g++ -shared -static-libgcc -static-libstdc++ -o libass-9.dll libass/.libs/*.o libass/x86/.libs/*.o -Wl,-static -lm -liconv -lfreetype -lbrotlidec -lharfbuzz -lfribidi -lfontconfig -lexpat -lfreetype -lpng -lbz2 -lz -lgdi32
```

However, the compiled libass.dll exports many symbols from its dependencies (e.g. `png_write_chunk`, `zlibVersion`):

![image](https://user-images.githubusercontent.com/5251264/215668988-865475e5-314f-4b2c-b19c-0b32e2ed6e18.png)

I tried to replace the dll in NVEnC with mine, and NVEnC still works fine. But, how can I compile a dll like yours that only exports `ass_*` symbols?

P.S. 日本語は少し理解できるので日本語を使っても問題ございません。

**Comment by rigaya** [comment]
Have you got file "libass-9.dll.def" in libass/.libs directory?

It lists which symbols to export.

I think by changing ```-shared``` to ```-shared libass/.libs/libass-9.dll.def``` shall solve the problem.

**Comment by ipid** [comment]
> Have you got file "libass-9.dll.def" in libass/.libs directory?
> 
> It lists which symbols to export.
> 
> I think by changing `-shared` to `-shared libass/.libs/libass-9.dll.def` shall solve the problem.

<br>

Thank you for your answer!

Your method didn't solve my problem:

1. I didn't get `libass-9.dll.def`, probably because my configure parameters are not the same as yours;
2. `g++ -shared ***.def` doesn't work.

But I finally found a method that works:

1. Configure: `CFLAGS="-fPIC -static-libgcc -static-libstdc++" ./configure --enable-shared=yes --enable-static=no`
2. Build all `*.o` files: `make -C libass libass.la`
3. Build with `g++ -shared -o libass-9.dll libass/.libs/*.o libass/x86/.libs/*.o -Wl,--output-def,libass.def -Wl,-static -static-libgcc -static-libstdc++ -lm -liconv -lfreetype -lbrotlidec -lharfbuzz -lfribidi -lfontconfig -lexpat -lfreetype -lpng -lbz2 -lz -lgdi32` to get a `.def` file; _(I specified `-lgdi32` here because I've built harfbuzz with GDI support.)_
4. Get a list of all `ass_*` functions from `libass.def`;
5. Prepare 2 text files named `retain-symbols-file.txt` and `version-script.txt`. The contents are:

The content of `retain-symbols-file.txt` consists of symbols that you want to export, with one symbol name per line:

```
ass_add_bitmaps_avx2
ass_add_bitmaps_c
...
ass_utf8_get_char
ass_utf8_put_char
```

Content of `version-script.txt` should follow this syntax:

```
LIBASS_1.0 {
  global:
    ass_add_bitmaps_avx2;
    ass_add_bitmaps_c;
    ...
    ass_utf8_get_char;
    ass_utf8_put_char;
  
  local:
    *;
};
```

One may use regex to create such a file. For example, it's possible to open the `.def` file with a text editor, then find all occurrences of `^\s+(?=ass_)[a-zA-Z0-9_]+` and copy them to a new file. VSCode users can press `Ctrl(Cmd)+Shift+L` to select all occurrences. Then, replace `$` with `;` to add a semicolon after each line.

6. Build the dll again with `g++ -shared -o libass-9.dll libass/.libs/*.o libass/x86/.libs/*.o -Wl,-static -Wl,--retain-symbols-file=retain-symbols-file.txt -Wl,--version-script=version-script.txt -static-libgcc -static-libstdc++ -lm -liconv -lfreetype -lbrotlidec -lharfbuzz -lfribidi -lfontconfig -lexpat -lfreetype -lpng -lbz2 -lz -lgdi32`.
7. These steps seem to build a perfect `libass-9.dll`, which has no extra DLL dependencies and exports only `ass_*` symbols:

![image](https://user-images.githubusercontent.com/5251264/215748848-38ee1985-f78e-4c53-ba29-bc86fe1f8e84.png)

8. Replace `libass-9.dll` next to NVEncC64.exe and `--vpp-subburn` works.

Thanks again for your lightning fast response!

**Comment by rigaya** [comment]
Thank you for sharing your workaround, might help me int he future!

I'm glad to hear you worked out fine.
